### ISSUE TITLE
BUG - Stream Deck Pedal icons appear in other device pages

### ISSUE THREAD

**Issue by skint007** [StreamController/StreamController#148]
**Describe the bug**
I have a Stream Deck mk2 and a Stream Deck Pedal. The icons on the pedal appear on the Stream Decks page. If I try to delete or move them on the stream deck, it affects the pedals page.

**To Reproduce**
1. Go to `Stream Deck Pedal` Page
2. Add any action on Pedal page.
3. Go to `Stream Deck` page.
4. Observe the icons are now on the other devices page.

**Expected behavior**
I expected the icons to stay on their devices pages.

**Screenshots**
![image](https://github.com/StreamController/StreamController/assets/37035851/b8096576-471d-49d5-8292-4fc6a4607173)
![image](https://github.com/StreamController/StreamController/assets/37035851/6207d0ca-874b-471c-b88e-470c66f8e85e)

**Additional context**
**Version**: 1.5.0-beta.5
I experienced it in beta4 also.

**Comment by Core447** [comment]
This is actually the expected behavior. In StreamController the pages are not device specific, in this case both devices are on the "Home" page and get therefore synced. To avoid this you have to create two separate pages. You can then configure which should be the default for which deck in the page settings (see the screenshot):
![screenshot](https://github.com/StreamController/StreamController/assets/100139110/1e6c7a3c-b1ff-4a97-96f0-297dd9eda18c)
