### ISSUE TITLE
Unexpected behaviour with Run Command & Gnome Window Calls

### ISSUE THREAD

**Issue by Lexipherous** [StreamController/StreamController#197]
**Describe the bug**
When using a Run Command and a Gnome Window Call to resize & move the window, the single Deck button will either open the target program OR move/resize it.

**To Reproduce**

1. Setup a `Run Command` action with `gnome-system-monitor` as the target
2. Added a delay to 2.0 seconds (uncertain if needed but helped determine if there was an issue or not)
3. Move and Resize action from Gnome Window Calls, with :
     1. Window Class Regex: `gnome-system-monitor`
     2. X Pos: 2500 (I have multiple monitors, so this might not work for everyone)
     3. Y Pos: 550
     4. Width: 900
     5. Height: 800

**Expected behavior**
When the Deck button is pressed, the expected behaviour would be to open said program, then after the delay (if it's even needed) move/resize the window.

**Screenshots**
Imgur link for convenience : https://imgur.com/a/Kz670Vb
![image](https://github.com/user-attachments/assets/8c137580-5d67-4ba5-bf14-4d7cb99733ca)
![image](https://github.com/user-attachments/assets/c2699ae0-18cd-4dec-aacb-01a842d2b058)
![image](https://github.com/user-attachments/assets/e2a98a35-0a9b-4ceb-a3ff-2aec907fdd02)
![image](https://github.com/user-attachments/assets/f40504f1-8295-4d81-9f39-021a022d50d4)

**Comment by Core447** [comment]
The problem is that "detached" is disabled in "Run Command", leading the action to wait until the command `gnome-system-monitor` is done, which is after the window has been closed. Enabling "Detached" solves this problem. I'll probably make "Detached" the default on future plugin versions.

Note: "Move and resize" **might** cause some problems with multi-monitor-setups, if this is the case for you using a separate "move" action after a short delay might fix this.

**Comment by Lexipherous** [comment]
This definitely sorts the issue out. Sorry for the late reply!
Thanks for the help :)

**Comment by Core447** [comment]
No problem, I'm glad it works now!
