### ISSUE TITLE
BUG: flatpak not launching

### ISSUE THREAD

**Issue by pnmtech** [StreamController/StreamController#88]
the flatpak is not launching at all.I downloaded it of if from gnome software it would silently not launch so i moved to the terminal and the information below was given

![image](https://github.com/StreamController/StreamController/assets/79518458/fa4474ca-86b6-48a6-b56e-803b12705a27)

i'm running fedora 40 on kernel 6.8.7 on an 11th gen i5

**Comment by pnmtech** [comment]
just tested it on a pop os vm that has not even been updated just a fresh copy of 22.04

**Comment by Core447** [comment]
`1.5.0-beta` has a bug preventing the start on X11 outside of Gnome. Please update to `1.5.0-beta.1`

**Comment by Arc86** [comment]
Running into a similar issue unfortunately.

- StreamController version:  1.5.0-beta.2
- OS: OpenSuse Tumbleweed
- Kernel: 6.8.8
- DE: KDE Plasma 6.0.4
- WM: Wayland

[Edit: Tried building from source instead of using Flatpak, however I am running into the same error]


![Screenshot_20240503_090214](https://github.com/StreamController/StreamController/assets/79000633/ce1371e2-95a7-4173-b5bd-ca826d073526)
![Screenshot_20240503_090546](https://github.com/StreamController/StreamController/assets/79000633/794f0a54-4ffc-4e61-a4ab-9ea93b780ce7)

**Comment by Core447** [comment]
This will be fixed with the next release. For now manually creating the folder `/home/jesper/.var/app/com.core447.StreamController/data/pages` should fix this issue.

**Comment by Core447** [comment]
a447f0cab0e4ed4a508ab6a79bf85fdd365131ef should fix this. Can you please try the source version again? Sorry for the inconveniences

**Comment by Arc86** [comment]
Thanks for your swift action! That fixed it for me! 
Loving the app, keep up the good work.

**Comment by Core447** [comment]
Thanks, I hope this fix will hit the flapak soon

**Comment by karoltheguy** [comment]
I'm on 1.5.0 beta 2 and I also had to create the below 2 folders before it actually runs:
/home/$USER/.var/app/com.core447.StreamController/data/settings/
/home/$USER/.var/app/com.core447.StreamController/data/settings/decks

**Comment by Core447** [comment]
> I'm on 1.5.0 beta 2 and I also had to create the below 2 folders before it actually runs:

This should be fixed in 1.5.0-beta.4
