### ISSUE TITLE
Block or queue sequential button presses for page change actions

### ISSUE THREAD

**Issue by v4u6h4n** [StreamController/StreamController#93]
Not sure how feasible this is, but I'm wondering if sequential button presses could be queued up, or ignored, if a page change action is one of a buttons actions. Currently if I press a button that runs a script and page change action, if there is some latency in the script execution, I can accidentally prematurely press a button before the page change action has completed, and I'm wondering if subsequent button presses on the page could be blocked or queued until the actions have been completed.

**Comment by Core447** [comment]
Adding this wouldn't be hard. However, I don't know if it would be really that useful. Maybe someone has an an action on the page change button that takes 20s to complete and it would be weird if the whole deck would be blocked for this time. And you can always move the page change action before the script so that it switches immediately.

**Comment by v4u6h4n** [comment]
Yeah, it would be useful for me because for some things I just have the page change action second, so that the page changing indicates the script was successful, but this might just be a bit too specific of a use case, for me, for anyone to be bothered with implementing ;-)

**Comment by Core447** [comment]
You can use the new `--change-page` api at the end of the script to accomplish this
